# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  teste-back-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: teste-back-mysql
    volumes:
      - teste-back-mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=teste-back
      - MYSQL_DATABASE=teste-back
      - MYSQL_USER=teste-back
      - MYSQL_PASSWORD=teste-back

  # PHP (with Caddy)
  app-p:
    image: ambientum/php:7.1-caddy
    container_name: teste-back-app
    volumes:
      - .:/var/www/app
    ports:
      - "8081:8080"
    links:
      - mysql